### ISSUE TITLE
README.md code snippets look ugly on PyPi

### ISSUE THREAD

**Issue by rc** [rc/scikit-umfpack#12]
Any ideas how to solve this? @timtadh

**Comment by timtadh** [comment]
Just get rid of the triple back-tick syntax. That way it will just be an indented code block. Only disadvantage is you will lose the syntax highlighting on github.

**Comment by rc** [comment]
Actually, there might be a better solution: http://stackoverflow.com/questions/10718767/have-the-same-readme-both-in-markdown-and-restructuredtext

**Comment by rc** [comment]
See also #15.
