### ISSUE TITLE
Provide wheels

### ISSUE THREAD

**Issue by cmutel** [rc/scikit-umfpack#2]
I know that this is currently not so easy, but providing wheels would make people's lives much easier, especially on Windows. There are a bunch of blog posts outlining how to compile on OS X and Windows, some older than others, but the short story is that this is difficult and intimidating for most.

Note that when building wheels, the compiled libraries (libamd, libcholmod, limunfpack, etc.) need to be copied into the wheel using [delocate](https://pypi.python.org/pypi/delocate) (see also [macpython](https://github.com/MacPython/wiki/wiki/Spinning-wheels)).

I have built a 64-bit wheel compatible with Macports and Homebrew for OS X 10.10 [available for testing here](https://dl.dropboxusercontent.com/u/1911208/scikit_umfpack-0.1-cp27-none-macosx_10_10_x86_64.whl). A fat binary (32/64 bit) single wheel can be built for OS X 10.6-10.10, and I will try to do that within the next week.

However, building for Windows is not so much fun, and help would be greatly appreciated. [This blog post](http://cowboyprogrammer.org/building-python-wheels-for-windows/) is great, but I am not sure how to compile SuiteSparse in the first place.

**Comment by cmutel** [comment]
Universal wheels for testing:

2.7: https://dl.dropboxusercontent.com/u/1911208/scikit_umfpack-0.1-cp27-none-macosx_10_10_x86_64.whl
3.4: https://dl.dropboxusercontent.com/u/1911208/scikit_umfpack-0.1-cp34-cp34m-macosx_10_6_intel.whl

**Comment by rc** [comment]
Thanks! I have no experience with wheels (and OS X). So how can I help? :)

**Comment by cmutel** [comment]
I will test the two wheels I posted on various VMs over the next week, and if they seem to work OK, then you can upload them directly to PyPI (where they will be installed for OS X people).

(Sorry if this wasn't clear, but the wheels contains the compiled SuiteSparse, so that there are no more steps than a simple ``pip install scikit-umfpack``).

I will look into building wheels on Windows - I have done some, but will have to also compile SuiteSparse. But I guess this takes some time.

**Comment by rc** [comment]
OK, I will upload the wheels as soon as they are ready. Thanks again, it will be really useful. I will update the installation instructions accordingly.

**Comment by cmutel** [comment]
I have test the 2.7 and 3.4 wheels, as well as convinced others to use them; I think they are ready to go.

**Comment by rc** [comment]
Thanks! I have just uploaded the wheels. Shall we close this?

**Comment by cmutel** [comment]
Closed for now - OS X wheels on pypi.

**Comment by kburns** [comment]
Would it be possible to expand the available wheels to include other versions of OS X, particularly macosx-10.10-x86_64?  Otherwise, do there happen to be any instructions for building based on an existing suite-sparse installation (which is easily available through home-brew on OS X)?  Thanks!

**Comment by cmutel** [comment]
Does the existing wheel not work? It should be "fat", i.e. both 32- and 64-bit compatible, and work for 10.6 through 10.10. See [Spinning wheels](https://github.com/MacPython/wiki/wiki/Spinning-wheels#question-will-pip-give-me-a-broken-wheel). You might have to upgrade your pip version, however, to at least 6.0.

**Comment by kburns** [comment]
Updating pip did the trick. Thanks!
